### ISSUE TITLE
Input for quadratic phase on "Advanced" menu

### ISSUE THREAD

**Issue by Delentropy** [magister-ludi/eigenbroetler#1]
Cannot input numeric values grater than 99 into constant, linear, and quadratic phase.

**Comment by magister-ludi** [comment]
This should now be fixed in commit https://github.com/magister-ludi/eigenbroetler/commit/814475ddf2cb2fe4d593a43ef4189f3dd7718d26 Where appropriate, spin box ranges have been increased to (2^32)-1.

**Comment by Delentropy** [comment]
Phase now allows large input values - excellent!
