### ISSUE TITLE
Input to chirp scaling also suffers from 99 value limit

### ISSUE THREAD

**Issue by Delentropy** [magister-ludi/eigenbroetler#2]
See similar problem with quadratic phase etc

**Comment by magister-ludi** [comment]
For the record, the comment above refers to https://github.com/magister-ludi/eigenbroetler/issues/1. This should now be fixed in commit https://github.com/magister-ludi/eigenbroetler/commit/814475ddf2cb2fe4d593a43ef4189f3dd7718d26 Where appropriate, spin box ranges have been increased to (2^32)-1.

**Comment by Delentropy** [comment]
Chirp now allows large input values  - excellent!
