### ISSUE TITLE
2DFFT  generating nan

### ISSUE THREAD

**Issue by Delentropy** [magister-ludi/eigenbroetler#3]
I generated a 1024 square image with NEW function cos(20.872*log(r))*cos(10*phi).
Then 2DFT does not display (just black) because of NaN's for pixel values.

**Comment by magister-ludi** [comment]
NaN's generally carry through calculations. In this case the most likely source is not the DFT, but the log(r) expression, when r==0. It would be straightforward to introduce some kind of "replace NaN" function, but maybe it would be better to replace log(r) by "if(r==0, X, log(r))", where X is an appropriate value (e.g. a large negative value, or even 0).

**Comment by Delentropy** [comment]
Whoops!  I should have checked more carefully.  I guess MisFits must ignore this problem point when it performs 2DFT on same FITS file and results in no NaNs?
